<?php

namespace ReclamationBundle\Repository;

/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function modifier($id,$type,$description,$file){
        $query = $this->getEntityManager()
            ->createQuery(" UPDATE ReclamationBundle:reclamation e SET e.type=:type,e.description=:description,e.fichier=:file where e.id=:id ")
            ->setParameter('id', $id)
            ->setParameter('description', $description)
            ->setParameter('type', $type)
            ->setParameter('file', $file);
        return $query->getResult();
    }
    public function consulter($id){
        $query = $this->getEntityManager()
            ->createQuery(" SELECT ReclamationBundle:reclamation e where e.id=:id ")
            ->setParameter('id', $id);
        return $query->getResult();
    }

}
