<?php

namespace UserBundle\Repository;

/**
 * amisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class amisRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAmis($user)
    {
        return $this->createQueryBuilder('c')
            ->where('c.actionuser != :user')
            ->andWhere('c.etat = 0')
            ->andWhere('c.firstuser = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

    public function getFriends($user)
    {
        return $this->createQueryBuilder('c')
            ->Where('c.etat = 1')
            ->andWhere('c.firstuser = :user')
            ->orWhere('c.etat = 1')
            ->andWhere('c.seconduser = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

}
