<?php

namespace UserBundle\Repository;

/**
 * myinterestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class myinterestsRepository extends \Doctrine\ORM\EntityRepository
{
}
