<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findbyusername($username)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM UserBundle:user p WHERE p.username LIKE :username'
            )
            ->setParameter('username', '%' . $username . '%')
            ->getResult();
    }
}
