<?php

namespace EventBundle\Repository;

/**
 * AppointmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
