<?php

namespace BlogBundle\Repository;

/**
 * CommentaireBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireBlogRepository extends \Doctrine\ORM\EntityRepository
{
}
