<?php

namespace CommandeBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function hasPanier($user)
    {
        $panier=$this->createQueryBuilder('c')
            ->where('c.user = :user')
            ->andWhere('c.etat = 0')
            ->setParameter('user',$user)
            ->getQuery()
            ->getSingleResult();
        return panier!=null;
    }
}
