<?php

namespace CommandeBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function hasPanier($user)
    {
        $panier=$this->createQueryBuilder('c')
            ->where('c.etat = 0')
            ->andWhere('c.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
        return count($panier)!=0;
    }

    public function getCommandes()
    {
        return $this->createQueryBuilder('c')
            ->where('c.etat != 0')
            ->getQuery()
            ->getResult();
    }
}
