gestion_produit_categorieproduit:
    resource: "@GestionProduitBundle/Resources/config/routing/categorieproduit.yml"
    prefix:   /admin/categorieproduit

gestion_produit_produit:
    resource: "@GestionProduitBundle/Resources/config/routing/produit.yml"
    prefix:   /

gestion_produit_homepage:
    path:     /
    defaults: { _controller: GestionProduitBundle:Default:index }

api_get_produits:
    path:     /api/produits
    defaults: { _controller: GestionProduitBundle:Produit:getAll }

api_get_categorie_produit:
    path:     /api/produit/categories
    defaults: { _controller: GestionProduitBundle:CategorieProduit:getAll }