<?php

namespace GestionProduitBundle\Repository;

/**
 * CommentaireProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
