<?php

namespace GestionProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
  /*  public function findEntitiesByString($str){
      return  $this->getEntityManager()
                    ->createQuery(
                        'SELECT p
                               FROM GestionProduitBundle:Produit p
                               WHERE p.nom LIKE:str'
                    )
          ->setParameter('str','%'.$str.'%')
          ->getResult();
    }*/
}
