<?php

namespace GestionProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function affichageCatDQL(){
        $qb=$this->getEntityManager()
                 ->createQuery(
                     "SELECT p from GestionProduitBundle:"
                 )
    }
}
