<?php

namespace GestionProduitBundle\Repository;

/**
 * RatingProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
