<?php

namespace AnimalBundle\Repository;

/**
 * CategorieAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
