<?php

namespace AnimalBundle\Repository;

/**
 * LikeAimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeAimalRepository extends \Doctrine\ORM\EntityRepository
{
}
